<!doctype html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <title>brewで入れたPythonでsqlite3が使えなくなってた | 旧それなりブログ</title>
  </head>
  <body>
    <header>
      <p>旧それなりブログの跡地</p>
      <nav>
        <ul>
          <li><a href="https://kjirou.github.io/old-sorenari-blog/">トップへ</a></li>
          <li><a href="https://kjirou.github.io/blog/">新ブログへ</a></li>
        </ul>
      </nav>
    </header>
    <article>
      <section>
        <h1>brewで入れたPythonでsqlite3が使えなくなってた</h1>
        <p>2013年4月10日</p>
      </section>
      <section>
        <div>
前は使えてたはずの import sqlite3 が<br />
いつの間にか _sqlite3.so へのリンクが切れてエラーが出ていました</p>
<pre>
$ python -c &#039;import sqlite3&#039;
Traceback (most recent call last):
  File &quot;&lt;string&gt;&quot;, line 1, in &lt;module&gt;
  File &quot;/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sqlite3/__init__.py&quot;, line 24, in &lt;module&gt;
    from dbapi2 import *
  File &quot;/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sqlite3/dbapi2.py&quot;, line 27, in &lt;module&gt;
    from _sqlite3 import *
ImportError: dlopen(/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_sqlite3.so, 2): Library not loaded: /usr/local/lib/libsqlite3.0.8.6.dylib
  Referenced from: /usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_sqlite3.so
  Reason: image not found
</pre>
</div>
<h3>解決</h3>
<div>
<a href="https://github.com/mxcl/homebrew/issues/17312" onclick="_gaq.push(['_trackEvent', 'outbound-article', 'https://github.com/mxcl/homebrew/issues/17312', 'SQLite update broke Python']);" target="_blank">SQLite update broke Python</a> に対応が書いてありました</p>
<p>以下を実行で直った</p>
<pre>
brew rm sqlite python python3
brew install python python3
</pre>
</div>

      </section>
    </article>
  </body>
</html>
